### ISSUE TITLE
CSV Airdrop App has been unusable in Gnosis Safe for 1 month+

### ISSUE THREAD

**Issue by mafer02198** [bh2smith/safe-airdrop#213]
hey all! when I try to use the CSV Airdrop app (which I used without issue up until the beginning of August) I get this error:

"invalid ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=providers/5.4.3)"
to be clear: I'm not using any ENS names just straight hexadecimal addresses

not being able to use this app anymore is a major issue actually as our DAO has many recurring payments that get made out of gnosis. any insight here?

**Comment by bh2smith** [comment]
Hey @mafer02198 thanks for letting us know. Will try and get this fixed ASAP. Could you provide a sample CSV that is failing with the error you describe?

**Comment by bh2smith** [comment]
The error looks like you are trying to use a column called "name" instead of "receiver". It would be very helpful if you could provide a sample CSV.

**Comment by schmanu** [comment]
If I change the column name to something else it also happens to me.
I think this should not happen. We should probably hard-code the header names so that they cant be changed to something else, because no other headers than the intended ones work.
If someone then pastes a CSV and we detect a second header we should crop it.
Also the error should at least be something meaningful. We should not even try to resolve any ens names if we find no address.
