### ISSUE TITLE
refactor web3provider / contracts into different methods to easily mock them for unittests

### ISSUE THREAD

**Issue by schmanu** [bh2smith/safe-airdrop#55]
Currently its hard to mock a web3provider, because we would have to mock the whole interface.
But we only need them to provide us with a contract and to give us the eth balance.
Therefore we should build interfaces, which encapsulate the huge web3provider.

**Comment by bh2smith** [comment]
We may not need to test the provider since it's coming from elsewhere, but what we can do to test balances is setup some ganache/hardhat testing. These tools would provide us a local blockchain in which we can deploy a safe and some ERC20s, mint some tokens to the safe and check its balance. However I do believe that the safe app sdk should provide versions of all these functions which are already tested. I'll have a look into it tomorrow and see what we can come up with.

**Comment by schmanu** [comment]
closed by #280
