### ISSUE TITLE
support ENS Names instead of token addresses

### ISSUE THREAD

**Issue by schmanu** [bh2smith/safe-airdrop#73]
We could use ethers.js to find out if the string is a valid address and use the ENS as a fallback.
Should be quite easy to implement and add some usability.

**Comment by bh2smith** [comment]
Yes! This would be a very nice feature to have. There are probably many other projects out there with existing implementations. I would like to see, in particular what happens with my personal address since I have 3 ENS records to my name each resolving to different addresses. On snapshot.page for example, the wrong name is displayed for my wallet. It appears to be fetching all the records I own and taking the first in alphabetical order.
